### ISSUE TITLE
The `reset_git_repo` function fails when HEAD is detached

### ISSUE THREAD

**Issue by behnazh-w** [oracle/macaron#530] opened 2023-10-26 23:45 UTC
If a repository is cloned by Macaron and then we checkout a commit which makes the `HEAD` detached, if any of the files are modified for some reason, the [reset_git_repo](https://github.com/oracle/macaron/blob/0f426982837708539fb64b76001b823b79596b0e/src/macaron/slsa_analyzer/git_url.py#L26) function fails to `stash` the changes and the second run of `Macaron` on that target fails.

Note that supporting commit checkout is crucial for [mapping artifacts to commits](https://github.com/oracle/macaron/pull/508).

To reproduce the error on the `staging` branch run: 

```bash
macaron -o output analyze -purl pkg:maven/org.opentest4j/opentest4j@1.2.0?type=jar --skip-deps
pushd output/git_repos/github_com/ota4j-team/opentest4j/
git checkout 75136304fab712895090c9c4678dc72ccbcb5e21
popd
macaron -o output analyze -purl pkg:maven/org.opentest4j/opentest4j@1.2.0?type=jar --skip-deps
```

**Comment by tromai** [comment] 2023-10-27 01:58
The issue can be reproduced in git version 2.25.1

**Comment by tromai** [comment] 2023-10-30 04:44
I have dig a bit into this issues with the repository [opentest4j](https://github.com/ota4j-team/opentest4j/), which correspond to the PURL `pkg:maven/org.opentest4j/opentest4j@1.2.0?type=jar` mentioned above.

Note: I highly recommend reading through this [article](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/) first to understand about the background of line endinds in git.

# The history of opentest4j
## At [96502f5](https://github.com/ota4j-team/opentest4j/commit/96502f5348b11dc86d5518af0c2132ed30e14525)

There is no `.gitattribute` for setting up line endings conversion.
The eol information for `gradlew.bat` and `gradle-wrapper.jar`. For more information on the output of `git ls-files`, please see [here](https://git-scm.com/docs/git-ls-files#Documentation/git-ls-files.txt---eol).

```
> git ls-files gradlew.bat --eol
i/lf    w/lf    attr/                   gradlew.bat
 
> git ls-files gradle/wrapper/gradle-wrapper.jar  --eol
i/-text w/-text attr/                   gradle/wrapper/gradle-wrapper.jar
```
- gradle.bat:
  - i/lf : The file gradlew.bat was initially checked into the repository with the line endings lf (which is Unix's line endings) → this is probably because the person who checked in this file use [git's line ending conversion feature](https://git-scm.com/docs/gitattributes#_checking_out_and_checking_in).
  - w/lf : When I checked out this commit, because there is no .gitattribute or any settings for git's line ending conversion feature, there is no line ending conversion happens → gradlew.bat in my working tree still keeps the **lf** line ending just like when it's added.
  - attr/ : no setting for line ending conversion is set.
- gradle/wrapper/gradle-wrapper.jar:
  - i/-text and w/-text: For binary files like images, note that you’ll see -text for both the index and working tree line endings. This means that Git correctly isolated those binary files, leaving them untouched.
  - attr/ : no setting for line ending conversion is set in .gitattribute.

## At [6ae5b16](https://github.com/ota4j-team/opentest4j/commit/6ae5b1623a72846e1e789c86f5676a6498e23129) - right after commit [96502f5](https://github.com/ota4j-team/opentest4j/commit/96502f5348b11dc86d5518af0c2132ed30e14525).

`gradlew.bat` and `gradle/wrapper/gradle-wrapper.jar` is again updated with new content. `gradlew.bat` new's content has CRLF endings.
There is still no .gitattribute in the repository.

```
> git ls-files gradlew.bat --eol
i/crlf  w/crlf  attr/                   gradlew.bat
 
> git ls-files gradle/wrapper/gradle-wrapper.jar  --eol
i/-text w/-text attr/                   gradle/wrapper/gradle-wrapper.jar
```

- gradle.bat:
  - i/crlf : The file gradlew.bat was checked into the repository with the line endings crlf (which is Window's line endings)
  - w/crlf : When I checked out this commit, because there is no .gitattribute or any settings for git's line ending conversion feature, there is no line ending conversion happens → gradlew.bat in my working tree will keeps the **crlf** line ending just like when it's added.
  - attr/ : no setting for line ending conversion is set.
- gradle/wrapper/gradle-wrapper.jar :
  - i/-text and w/-text : For binary files like images, note that you’ll see -text for both the index and working tree line endings. This means that Git correctly isolated those binary files, leaving them untouched.
  - attr/ : no setting for line ending conversion is set in .gitattribute

## At [f2c384f3](https://github.com/ota4j-team/opentest4j/commit/f2c384f37cf1a02b32cceb1636ab1036b25938fb) - right after commit [6ae5b16](https://github.com/ota4j-team/opentest4j/commit/6ae5b1623a72846e1e789c86f5676a6498e23129).

The .gitattribute file is added with the following content.

```
* text eol=lf
*.bat eol=crlf
```

- `* text eol=lf`: for all files, set the text option:
  - > Setting the text attribute on a path enables end-of-line conversion on checkin and checkout as described above. Line endings are normalized to LF in the index every time the file is checked in, even if the file was previously added to Git with CRLF line endings.
  - `eol=lf` when checked out in a local repository, make git convert all line endings into lf .
- `*.bat eol=crlf`: for all files that ends with .bat , when checked out in a local repository, make git convert all line endings into lf. This eol=crlf overrides the default eol=lf for bat files only.

Therefore when you check out this commit:

```
> git ls-files gradlew.bat --eol
i/crlf  w/crlf  attr/text eol=crlf      gradlew.bat

> git ls-files gradle/wrapper/gradle-wrapper.jar  --eol
i/-text w/-text attr/text eol=lf        gradle/wrapper/gradle-wrapper.jar
```

- gradle.bat:
  - i/crlf : The file gradlew.bat was checked in with line endings crlf in commit 6ae5b16
  - w/crlf : When I checked out this commit, because there is no .gitattribute or any settings for git's line ending conversion feature, there is no line ending conversion happens → gradlew.bat  in my working tree still keeps the crlf line ending just like when it's added.
  - attr/text eol=crlf : the text setting is applied for this file, when this file is checked out in the local repo, git will convert all line endings of gradle.bat into crlf .
- gradle/wrapper/gradle-wrapper.jar :
  - i/-text and w/-text : For binary files like images, note that you’ll see -text for both the index and working tree line endings. This means that Git correctly isolated those binary files, leaving them untouched.
  - attr/text eol=lf : the text setting is applied for this file (however, text should only be used for text files, not binaries, so this is an error on the author side).

Now, if you freshly clone the repository and checkout commit [f2c384f3](https://github.com/ota4j-team/opentest4j/commit/f2c384f37cf1a02b32cceb1636ab1036b25938fb):

```
> git status
HEAD detached at f2c384f
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   gradle/wrapper/gradle-wrapper.jar
        modified:   gradlew.bat
 
no changes added to commit (use "git add" and/or "git commit -a")
```

This is the same behavior specified in this Github issue.
I have tested and the same behavior appears in git:
  - 2.25.1
  - 2.39.3

# Why does this happen in the first place?
In commit [f2c384f3](https://github.com/ota4j-team/opentest4j/commit/f2c384f37cf1a02b32cceb1636ab1036b25938fb) as I mentioned above, even though the .gitattribute files is added, theses changes won’t take effect immediately for files checked into Git prior to the addition of .gitattributes. This will mean that gradlew.bat are stilled stored with line ending crlf in the index of the repository.

From my understanding, the eol for gradlew.bat within the index of the repository is crlf, but because `attr/text eol=crlf` makes sure that the content of this file when checked into the repository, its eol will be converted into lf by git. The converted version with lf eol will definitely different from the existing crlf versions of `gradlew.bat` inside the index of the repository → I think this make Git treat them as 2 "versions" with different eol settings.

This is consistent with an existing Stackoverflow [thread](https://stackoverflow.com/questions/72869783/git-apparently-keeps-saying-that-a-file-has-been-modified-when-it-has-not).

One thing I know exactly sure is that the author that made the addition of .gitattribute in commit [f2c384f3](https://github.com/ota4j-team/opentest4j/commit/f2c384f37cf1a02b32cceb1636ab1036b25938fb) didn't run `git add --renormalize .` as recommended [here](https://git-scm.com/docs/gitattributes#_end_of_line_conversion) to make sure that all previous versions of `gradlew.bat` and `gradle/wrapper/gradpe-wrapper.jar` got normalized according to .gitattribute.

In later commits:
- [37106d85](https://github.com/ota4j-team/opentest4j/commit/37106d85c85e9cbee06495616d47601ab16fa877): `gradlew.bat` eol in the index of the repository is updated to be lf.
- [6aa4af84](https://github.com/ota4j-team/opentest4j/commit/6aa4af8457ebacb9a565401a1ce0f7f443dcdb7e): the content of `.gitattribute` is modified to correctly assign `gradle/wrapper/gradpe-wrapper.jar` as a binary and therefore ignored from git's end of lines conversion.
- Therfore, if your check out commits after these two commits, the issues will not happen.

# How can we address this?
We can run `git checkout -f` when checking out banches or commits so that it will checkout regardless of the issue mentioned above.
We can safely do this as we have run `git stash` and `git reset` beforehand.

**Comment by behnazh-w** [comment] 2023-10-30 23:33
@tromai thanks for looking into the issue. It's still unclear to me why these two files remain modified after calling the [reset_git_repo](https://github.com/oracle/macaron/blob/0f426982837708539fb64b76001b823b79596b0e/src/macaron/slsa_analyzer/git_url.py#L26) function. Do you have any idea?

**Comment by tromai** [comment] 2023-10-31 00:44
> It's still unclear to me why these two files remain modified after calling the [reset_git_repo](https://github.com/oracle/macaron/blob/0f426982837708539fb64b76001b823b79596b0e/src/macaron/slsa_analyzer/git_url.py#L26) function. Do you have any idea?

The root cause of the issue:
- In the `.gitattribute` file, `gradlew.bat` is configured with line ending normalization by git. 
  
  ```
  * text eol=lf
  *.bat eol=crlf
  ``` 
  - This configuration will ensure that: 1. When `gradlew.bat` is checked into the index of the repository, it must always be converted to use `lf`, when this file is checked out into the working tree, it must be converted to `crlf` again.
- However, due to mis-configuration:
  - In the index of the repository for `gradlew.bat`, it is still stored with `crlf` (due to some mis-configuration from the author side).
  - In the working tree (a.k.a the file system where the files are checked out),  `gradlew.bat` is stored with `crlf` (as expected by the configuration in `.gitattribute`).
- Therefore, whenever git try to check if there is any changes to `gradlew.bat` in the working tree compared to `gradlew.bat` in the index of the HEAD commit, it will try to convert the `gradlew.bat` in the working tree (with `crlf`) to `lf`. This will obviously make it different compared to the `gradlew.bat` currently in the index with `crlf` -> This explains that running git commands that need to check the state of files in the working tree (e.g `git status`). `gradlew.bat` will appear as though it has been changed.

Now let's get back to the [reset_git_repo](https://github.com/oracle/macaron/blob/0f426982837708539fb64b76001b823b79596b0e/src/macaron/slsa_analyzer/git_url.py#L26)  function. This function called within Macaron at the moment will try to reset both the **index** and the **working tree** of the repository it's analyzing.
This reset operation can't help change the condition which trigger the issue I describe above:
- Resetting the index would make `gradlew.bat`  stored with `crlf` in the index still.
- Resetting the working tree doesn't help because git would then again try to convert `gradlew.bat` to `lf`. 

> So, if we do that, we won't need to stash and reset. But it would be good to understand the root cause first.

Yes this is true. In theory, we wouldn't need to reset at all (given that we have created a stash) before trying to checkout with the `--force` flag. I could try to remove the resetting operation and test if everything works normally.

Furthermore, for optimization, when Macaron deals with repositories that it caches inside `output/git_repos` that are not local repositories provided by the users, we could just ignore stashing. This is because those repositories are only touched by Macaron. If the user really wants to do that, they must know what they are doing and we don't need to handle those cases.

**Comment by behnazh-w** [comment] 2023-10-31 04:17
Thanks for the clarification.
>we wouldn't need to reset at all (given that we have created a stash) before trying to checkout with the --force flag.

I don't think we even need to stash if we use `checkout` with the `--force` flag.

**Comment by tromai** [comment] 2023-10-31 04:23
> I don't think we even need to stash if we use checkout with the --force flag.

That's correct. The reason the stash command was used is because we were trying to save any local changes (propably made by the users) to the repository we are analyzing. This is mostly specific for the use case where the user wants to provide a local repository path to Macaron. If we decide that we wouldn't be responsible for losing any local changes in the repository the user want to analyze, we could avoid stashing and put some documentation saying that Macaron could potentially remove any local non-committed changes.

**Comment by behnazh-w** [comment] 2023-10-31 04:25
Sounds good. We should add a note or warning to docs for the local repo use case.

**Closed** 2023-11-03 01:43 UTC
Labels: bug, git_operations
